# -*- coding: utf-8 -*-
"""pallette.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQQ8v1SnGx75YGvs8lSFL2cp4taP8Z0r
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

path = "outfit2.jpg"
size = (200, 200)
image = cv2.imread(path)
image = cv2.resize(image, size)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

h, w, channels = image.shape
image = image[int(h*0.1):int(h*0.9), int(w*0.15):int(w*0.85)]

pixels = image.reshape((-1,3))
pixels = np.float32(pixels)
pixels = pixels[np.any(pixels < 240, axis = 1)]

k = 5

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 1.0)

compactness, labels, centers = cv2.kmeans(pixels, k, None, criteria, 5, cv2.KMEANS_RANDOM_CENTERS)

centers = centers.astype(int)

plt.figure(figsize=(8,2))
for i in range(k):
  plt.subplot(1, k, i+1)
  plt.imshow([[centers[i]]])
  plt.axis("off")

plt.show()

hex = ['#%02x%02x%02x' % tuple(c) for c in centers]
print('hex codes:', hex)